### ISSUE TITLE
External Feedback #1

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#22]
The graphics in the site are often displayed at the wrong resolution making them blurry.

The home page looks like it contains a carousel because the 3 stories at the top have a large arrow next to them. I suggest you remove the arrows and just let people click on the title of the story to get more information.

The history of GODAN contains a map and timeline. The layout and interaction design of this is slightly strange – I suggest you have another look at how it displays.

The Join as  GODAN partner link to ‘more information’ just takes you back to the home page so it is circular.

Whenever you select a story or item you lose the top navigation focus. Is this because the stories appear under several headings? I found it difficult to know if I was looking at a piece of research, or news, or other resource.

When you select a piece of research the headings of Date, GODAN area and Useful for Activity are centred on the page although the items under it are left justified. I suggest you make the headings left justified as well to make it easier to read.

The headings of GODAN area and Keywords appears in different places depending on what you select. This should be consistent.
http://test-godan-new.pantheonsite.io/news/new-research-shows-impact-open-data-agriculture-and-nutrition
http://test-godan-new.pantheonsite.io/documents/how-can-we-improve-agriculture-food-and-nutrition-open-data
This last item doesn’t actually include the document – just the headings that describe it. Is this correct? Clicking on the actual paper graphic just takes you to the graphic of the cover.

The search box within the sections – does this relate to that section only? Need to make this clearer.

**Comment by valeriapesce** [comment]
Could you at a certain point consolidate the comments and select only those that are really important and on which you agree?

If possible, things that were agreed in the past (like the graphic design, with the arrows on the hompeage) should be changed now only if there is a strong reason.

And we should separate comments on technical issues and comments on contents so that AgroKnow focuses only on technical issues.

For instance, content issues: 
a) the blurry images (they have to be replaced, the size was agreed upon when it was agreed on the proposed graphic design))
b) the history of GODAN timeline: that was probably created with some plugin  and then embedded in Wordpress: the content has to be manually edited to make it look better.

It si important that we give a precise and essential list to Agroknow if we want to finish everything before Easter.

**Comment by dianaszpotowicz** [comment]
Ok - I was just emailed this but the rest of the comments will come in through a SurveyMonkey so we should have more consolidated comments in the future.

**Comment by valeriapesce** [comment]
OK, for the moment I collected feedback from AgroKnow on each point:

1) The home page looks like it contains a carousel because the 3 stories at the top have a large arrow next to them. I suggest you remove the arrows and just let people click on the title of the story to get more information.
_It would look like a carousel if it had left and right arrows for the whole banner, but having three arrows, one for each item, should not create any confusion._
(I agree with AK)

2) The history of GODAN contains a map and timeline. The layout and interaction design of this is slightly strange – I suggest you have another look at how it displays.
_This is a content issue: the timeline was created originally with an external tool and embedded._

3) The Join as GODAN partner link to ‘more information’ just takes you back to the home page so it is circular.
_To which page should that link go?
In the old webiste, there was this page:
http://www.godan.info/partners/become-a-godan-partner/
which is also on the new website:
http://test-godan-new.pantheonsite.io/pages/thinking-becoming-godan-partner
We could link it to that for the moment._

4) Whenever you select a story or item you lose the top navigation focus. Is this because the stories appear under several headings? I found it difficult to know if I was looking at a piece of research, or news, or other resource.
**_Fixed_**

5) When you select a piece of research the headings of Date, GODAN area and Useful for Activity are centred on the page although the items under it are left justified. I suggest you make the headings left justified as well to make it easier to read.
_**We can fix this**_

6) The headings of GODAN area and Keywords appears in different places depending on what you select. This should be consistent.
http://test-godan-new.pantheonsite.io/news/new-research-shows-impact-open-data-agriculture-and-nutrition
http://test-godan-new.pantheonsite.io/documents/how-can-we-improve-agriculture-food-and-nutrition-open-data
_**We can fix this**_

7) This last item doesn’t actually include the document – just the headings that describe it. Is this correct? Clicking on the actual paper graphic just takes you to the graphic of the cover.
_The link to the document is below the cover image._
**_Link to the cover image: fixed_**.

8) The search box within the sections – does this relate to that section only? Need to make this clearer.
_How?_
