### ISSUE TITLE
Resources in news stories

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#23]
This is more of a question - when we select resources to highlight for news stories, are they supposed to show up in the published story?

For example, under the 'Open call for web series' story - I've selected a few resources to highlight, but only keywords show up.

![resources](https://cloud.githubusercontent.com/assets/17909896/13929933/8ee228aa-ef94-11e5-8e67-9a3bcd9bd639.JPG)

**Comment by valeriapesce** [comment]
Hi Diana,

not sure if I understand this.

When you say "under the 'Open call for web series' story - I've selected a few resources to highlight", how did you select resources under that story? I don't think it's possible to select resources from another resource/news.

Perhaps you refer to the selection of "type of resource" in the news item?
In that dropdown, you define which type of resource you're posting (so in this case the call for the web series) and you therefore determine where it will be displayed and under which "facet" it will be found.
In this case, if you tag the news item as "Success stories", it will appear in the Success stories page and not in the News anymore. If you don't select a special type of resource, then it's considered a normal news item and appears only under News.

These things can be fine-tuned over time, once you know your needs better. For instance, it can be decided that if a news item is tagged as Success story it will appear both under Success stories and under news, but the rules will have to be designed carefully to avoid too much duplication (for instance, a news item tagged with many types could appear in News, Success stories and Research).
It would be useful to write down definitions of the various types of content (News item, blog post, document, presentation...) and of the various types of resource (case study, research etc.) and decide which appear where.

These types will intersect, because a blog post can be a resource of type "research" or a success story, but also a document can be an advocacy resource or a case study, and the same for a presentation.

Other general rules:

Regarding the highlighted items (those displayed in the "featured" strips):
When you select resources to highlight or to "feature" "in the relevant section", it means that the resource will end up in the Featured strip in the page that shows that type of resource (so if you tick Featured in relevent section for a resource that you tag as "success story", that resource will be displayed in the featured strip in the Success stories page.)

Among those that you selected as featured, only maximum the latest 4 will appear in the featured strip, so if you want to replace one with another you will have to un-tick the one that you don't want to see featured.

I think Agroknow wrote these things in soem document, but you can have a separate skype call to recap all the rules.

**Comment by stoitsis** [comment]
We agree in general with Valeria. @dianaszpotowicz the document with the instructions for content generation and organisation is here https://docs.google.com/document/d/1oTPrEmm5TBQmYZabcMR5hQDxtsHP4LYGwwiXEjwspak/edit
Let us know if you need any clarification.
