### ISSUE TITLE
DFID partner - org info will not change in CRM

### ISSUE THREAD

**Issue by anabrandusescu** [godanSec/Website#24]
Info shows incorrectly even though I changed it twice in the edits within CRM.
![dfid-error](https://cloud.githubusercontent.com/assets/3058770/13946314/19c1b11e-f014-11e5-96d1-83f5cfd5c300.jpg)

**Comment by VTsantilis** [comment]
Organization description is updated from civicrm "Organization info" from the civicrm edit if is not empty.
Try to add the information as shown in this screenshot. Inline edit will be available soon.
![edit dfid department for international development uk godan](https://cloud.githubusercontent.com/assets/8608412/13951988/a3c69cda-f03c-11e5-8d8c-ee5a0abe3f4b.png)

**Comment by anabrandusescu** [comment]
Yes, the organisation info is empty in the CRM but not on the website. When you hover over DFID it gives you Development Gateway's description. (See screenshot in my previous comment.)

This was also tested in CRM edit mode, as well as inline.

**Comment by VTsantilis** [comment]
Yes the description is correct since it exists here http://test-godan-new.pantheonsite.io/node/3386/edit
Probably you added that description from this link. In order to change it you will have to provide the organization info in the respective box in crm. Did you add any text there and not saved? Inline edit not working for now it will be later available, try from the edit button, you can add the text here too and i will try to update if you want

**Comment by anabrandusescu** [comment]
Ok it's clear now. I thought that changing it solely in CRM will change the website description too but its not the case. I have to change both CRM and description within the website. 

Thanks.

**Comment by anabrandusescu** [comment]
Can you create a feature that when a change is made in CRM (for organisation info) to override the website content?

**Comment by VTsantilis** [comment]
No you will have to update just crm (website desc is overriden), but since for the specific contact there is a description and crm desc is **empty**  it does not update the content. it will be overriden as soon as you add text in crm organization info

**Comment by anabrandusescu** [comment]
ok, sounds good. thanks!
