### ISSUE TITLE
Event page picture titles

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#29]
I'm not sure if this is intentional, but if the title for an event is longer than three lines, it looks like the words go out of the border of the photo (see image)

![events page titles](https://cloud.githubusercontent.com/assets/17909896/14106019/ce2395d6-f5a6-11e5-8ef2-ddb189b12847.JPG)

**Comment by valeriapesce** [comment]
This happens at lower resolutions and is due to the number of characters we decided to show in the boxes.
We could show fewer characters, but then at higher resolutions there will be some empty room in the title box.

At which resolution did you get this screenshot?
We could ask AK to do some tests with fewer characters and see how it goes at different resolutions.
