### ISSUE TITLE
Broken link in a news page

### ISSUE THREAD

**Issue by stoitsis** [godanSec/Website#47]
@dianaszpotowicz @anabrandusescu  we noticed that in this page http://www.godan.info/news/join-planning-committee-godan-2016-summit there is a Sign up link that is broken. Maybe you want to correct this and add the correct link which is http://www.godan.info/content/sign-here-join-godan-partner

**Comment by dianaszpotowicz** [comment]
Hi Giannis,

I think those are two different links. The first one is broken / probably taken down because we do not want anyone else joining the planning committee at this stage. So we would just want to the sign up link taken away completely. Would it be possible to do this?

The sign up to join and be a GODAN partner link is something separate from the Summit completely, and doesn’t need to be advertised on the Summit page.

Thanks for flagging this for us.

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec

**Comment by stoitsis** [comment]
@dianaszpotowicz you can edit the page http://www.godan.info/node/1930/edit and remove these links by also rephrasing the last sentence. I understand that this page is not useful any more but deleting it is not the best option. Its better to keep it for the records and for SEO.

**Comment by dianaszpotowicz** [comment]
Hmm but we were asked to take it down. Can we just archive it / hide the page completely so it's not deleted but completely hidden from the user?

**Comment by stoitsis** [comment]
@dianaszpotowicz done. I just unpublished it.

**Comment by dianaszpotowicz** [comment]
Wonderful, thank you.

Kind regards,

Diana Szpotowicz

Strategic Communications Advisor 

Global Open Data for Agriculture and Nutrition (GODAN)

Diana.Szpotowicz@godan.info

+44 01491 829315

@godanSec
