### ISSUE TITLE
website working group page issues

### ISSUE THREAD

**Issue by dianaszpotowicz** [godanSec/Website#8]
Comments from Andre:

I suggest they be left aligned, not centred.

First the name of the group, in bold.

Then under it a short paragraph describing it.

We also need a contact person, clickable email address (for each group)

Then eventually space for ‘ more’  besides each so that if one wants to know what the group is doing, access its blog/hackpad, that it be possible.

So even I f we don t have all this info right now, we should put dummy links so that the space is earmarked for it.

**Comment by valeriapesce** [comment]
The alignment cna be changed right away.

The following tasks will be completed later, as these functionalities were not requested before and have to do with the content):
- We also need a contact person, clickable email address (for each group)
- Then eventually space for ‘ more’ besides each so that if one wants to know what the group is doing, access its blog/hackpad, that it be possible.

**Comment by anabrandusescu** [comment]
We will need some time (and permission) to collect all of the contact person details.
